campaignchain_activity_linkedin_share_news_item_new:
    pattern:  /activity/linkedin/share-news-item/new
    defaults: { _controller: CampaignChainActivityLinkedInBundle:ShareNewsItem:new }

campaignchain_activity_linkedin_share_news_item_edit:
    pattern:  /activity/linkedin/share-news-item/{id}/edit
    defaults: { _controller: CampaignChainActivityLinkedInBundle:ShareNewsItem:edit }

campaignchain_activity_linkedin_share_news_item_edit_modal:
    pattern:  /modal/activity/linkedin/share-news-item/{id}/edit
    defaults: { _controller: CampaignChainActivityLinkedInBundle:ShareNewsItem:editModal }

campaignchain_activity_linkedin_share_news_item_edit_api:
    pattern:  /api/private/activity/linkedin/share-news-item/byactivity/{id}/edit
    defaults: { _controller: CampaignChainActivityLinkedInBundle:ShareNewsItem:editApi }
    options:
        expose: true

campaignchain_activity_linkedin_share_news_read:
    pattern:  /activity/linkedin/share-news-item/{id}
    defaults: { _controller: CampaignChainActivityLinkedInBundle:ShareNewsItem:read }